import { useState } from "react";
import { BotMessageSquare, HeartHandshake, Send, Sparkles } from "lucide-react";

type SupportToolsPageProps = { mode: "assistant" | "donate" };

export function SupportToolsPage({ mode }: SupportToolsPageProps) {
  const [question, setQuestion] = useState("");
  const [sent, setSent] = useState(false);
  const isAssistant = mode === "assistant";

  if (!isAssistant) return <section className="mx-auto max-w-3xl px-5 py-8 lg:px-8"><div className="overflow-hidden rounded-[28px] bg-[#1c075c] p-7 text-white shadow-xl sm:p-10"><div className="flex size-14 items-center justify-center rounded-2xl bg-[#ffe51c] text-[#1c075c]"><HeartHandshake size={28}/></div><p className="mt-7 text-[10px] font-bold tracking-[.18em] text-[#ffe51c]">SUPPORT BY.CASHIER</p><h2 className="mt-3 font-['Space_Grotesk'] text-3xl font-bold">Donate via Saweria</h2><p className="mt-4 max-w-xl text-sm leading-6 text-white/65">Dukungan Anda membantu pengembangan fitur BY.CASHIER untuk UMKM. Ikon donasi sudah aktif di menu; tautan Saweria resmi perlu ditambahkan oleh Founder agar tombol pembayaran mengarah ke akun yang benar.</p><div className="mt-8 rounded-2xl border border-white/10 bg-white/5 p-5"><p className="text-sm font-bold">Tautan donasi belum dikonfigurasi</p><p className="mt-1 text-xs leading-5 text-white/55">Masukkan URL profil Saweria BY.CASHIER di konfigurasi aplikasi sebelum membagikannya ke pengguna.</p></div></div></section>;

  return <section className="mx-auto max-w-3xl px-5 py-8 lg:px-8"><div className="rounded-[28px] border border-[#e6ddf4] bg-white p-6 shadow-sm sm:p-8"><div className="flex items-start gap-4"><div className="grid size-12 shrink-0 place-items-center rounded-2xl bg-[#1c075c] text-[#ffe51c]"><BotMessageSquare size={23}/></div><div><p className="text-[10px] font-bold tracking-[.18em] text-[#7653ad]">BY.CASHIER ASSIST</p><h2 className="mt-1 font-['Space_Grotesk'] text-2xl font-bold text-[#1c075c]">Asisten AI operasional</h2><p className="mt-2 text-sm leading-6 text-gray-500">Tulis pertanyaan tentang alur kasir, stok, laporan, atau menu. Integrasi model AI dapat dihubungkan dari backend saat kredensial sudah siap.</p></div></div><div className="mt-7 rounded-2xl bg-[#f4f0fb] p-4 text-sm text-[#4d3378]"><span className="inline-flex items-center gap-2 font-bold"><Sparkles size={16} className="text-[#8d63d8]"/>Siap membantu operasional toko.</span><p className="mt-2 text-xs leading-5 text-[#765b9d]">Panel ini belum mengirim data ke AI eksternal sebelum endpoint server dikonfigurasi.</p></div><div className="mt-5 flex gap-3"><input value={question} onChange={event => { setQuestion(event.target.value); setSent(false); }} onKeyDown={event => { if (event.key === "Enter" && question.trim()) setSent(true); }} placeholder="Contoh: bagaimana cek stok menu hari ini?" className="min-w-0 flex-1 rounded-2xl border border-[#ded5ef] px-4 py-3 text-sm text-[#1c075c] outline-none transition focus:border-[#7c5cbf]"/><button onClick={() => question.trim() && setSent(true)} className="grid size-12 place-items-center rounded-2xl bg-[#ffe51c] text-[#1c075c] transition hover:brightness-105" aria-label="Kirim pertanyaan"><Send size={18}/></button></div>{sent && <p className="mt-4 rounded-xl bg-[#edf9f2] px-4 py-3 text-xs leading-5 text-[#26704a]">Pertanyaan tersimpan di panel. Hubungkan endpoint AI di backend untuk menerima jawaban otomatis.</p>}</div></section>;
}
